catalog/urls.py
from django.urls import path

from .views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookYearOfExperienceUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    AssignDeleteDishView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dishtype/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dishtype/<int:pk>//detail/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "dishtype/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dishtype/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dishtype/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dish/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dish/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish/<int:pk>/toggle-assign/",
        AssignDeleteDishView.as_view(),
        name="toggle-dish-assign",
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookYearOfExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
]

app_name = "catalog"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/cook_confirm_delete.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} Cook delete {% endblock title %}

{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Delete cook?</h4>
            </div>
            <div class="card-body">
              <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Yes" class="btn btn-danger">
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Restaurant kitchen service</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/pages/cook_detail.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Dish List {% endblock title %}

{% block body %} {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section class="pt-9 pb-5">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-6">
        <h1 class="row d-flex justify-content-center">
          {{ cook.username }}
          <a href="{% url 'catalog:cook-update' pk=cook.id %}" class="btn btn-primary link-to-page">
            Update cook's years of experience
          </a>
        </h1>
        <p><strong>Username:</strong> {{ cook.username }}</p>
        <p><strong>First name:</strong> {{ cook.first_name }}</p>
        <p><strong>Last name:</strong> {{ cook.last_name }}</p>
        <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
        <p>
          <strong>Dishes:</strong>
            {% for dish in cook.dishes.all %}
              {{ dish.name }}{% if not dish == cook.dishes.last %}, {% endif %}
            {% empty %}
              No dishes!
            {% endfor %}
        </p>
          <h3>
            <a href="{% url 'catalog:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
              Delete cook
            </a>
          </h3>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/pages/cook_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} {{ object|yesno:"Update,Create" }} {% endblock title %}

{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">{{ object|yesno:"Update,Create" }}</h4>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Save</button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Restaurant kitchen service</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/pages/cook_list.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cook List {% endblock title %}

{% block body %} {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}
  
<section class="pt-9 pb-5">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-6">
        <h1 class="row justify-content-center">
          Cooks
          <a href="{% url 'catalog:cook-create' %}" class="btn btn-primary">
            Create cook
          </a>
        </h1>
        {% if cook_list %}
          {% include "includes/search_from.html" %}
          <table class="table">
            <tr>
              <th>ID</th>
              <th>Username</th>
              <th>First name</th>
              <th>Last name</th>
              <th>Years of experience</th>
            </tr>
          {% for cook in cook_list %}
            <tr>
              <td>{{ cook.id }}</td>
              <td><a class="link-primary" href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
              <td>{{ cook.first_name }}</td>
              <td>{{ cook.last_name }}</td>
              <td>{{ cook.years_of_experience }}</td>
            </tr>
          {% endfor %}
          </table>
        {% else %}
          <p>There are no cooks.</p>
        {% endif %}
      
        {% include "includes/pagination.html" %}
      
      </div>
    </div>
  </div>
</section>
  
{% endblock content %}
  

templates/pages/dish_confirm_delete.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} Delete dish {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Delete dish?</h4>
            </div>
            <div class="card-body">
              <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Yes" class="btn btn-danger">
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Restaurant kitchen service</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/pages/dish_detail.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Dish List {% endblock title %}

{% block body %} {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section class="pt-9 pb-5">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-6">
        <h1 class="row d-flex justify-content-center">
          {{ dish.name }}
          <a href="{% url 'catalog:dish-update' pk=dish.id %}" class="btn btn-primary link-to-page">
            Update dish
          </a>
        </h1>
          <p><strong>ID:</strong> {{ dish.id }}</p>
          <p><strong>Name:</strong> {{ dish.name }}</p>
          <p><strong>Description:</strong> {{ dish.description }}</p>
          <p><strong>Price:</strong> {{ dish.price }}</p>
          <p><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>
          <p><strong>Cooks:</strong>
            {% for cook in dish.cooks.all %}
              {{ cook.username }}{% if not cook == dish.cooks.last %}, {% endif %}
            {% empty %}
              No cooks!
            {% endfor %}
          </p>
        <h3>
          <form action="{% url 'catalog:toggle-dish-assign' pk=dish.id %}" method="post">
            {% csrf_token %}
            {% if dish in user.dishes.all %}
              <button class="btn btn-danger link-to-page">
                Delete me from this dish
              </button>
            {% else %}
              <button class="btn btn-success link-to-page">
                Assign me to this dish
              </button>
            {% endif %}
          </form>
        </h3>
        <h3>
          <a href="{% url 'catalog:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
            Delete dish
          </a>
        </h3>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/pages/dish_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} {{ object|yesno:"Update,Create" }} {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">{{ object|yesno:"Update,Create" }}</h4>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Save</button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Restaurant kitchen service</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/pages/dish_list.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Dish List {% endblock title %}

{% block body %} {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section class="pt-9 pb-5">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-6">
        <h1 class="row d-flex justify-content-center">
          Dishes
          <a href="{% url 'catalog:dish-create' %}" class="btn btn-primary link-to-page">
            Create dish
          </a>
        </h1>

    {% include "includes/search_from.html" %}

        {% if dish_list %}
          {% for dish in dish_list %}
            <div style="border-bottom:1px solid #ccc; margin-bottom: 15px">
              <p><strong>ID:</strong>{{ dish.id }}</p>
              <p><strong>Name:</strong><a class="link-primary" href="{% url 'catalog:dish-detail' pk=dish.pk %}"> {{ dish.name }}</a></p>
              <p><strong>Description:</strong> {{ dish.description }}</p>
              <p><strong>Price:</strong> {{ dish.price }}</p>
              <p><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>
            </div>    
          {% endfor %}
        {% else %}
          <p>There are no dishes.</p>
        {% endif %}

        {% include "includes/pagination.html" %}

      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/pages/dish_type_confirm_delete.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_filters %}

{% load static %}

{% block title %} Delete dish {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Delete dish type?</h4>
            </div>
            <div class="card-body">
              <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Yes" class="btn btn-danger">
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Restaurant kitchen service</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/pages/dish_type_detail.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Dish List {% endblock title %}

{% block body %} {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section class="pt-9 pb-5">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-6">
        <h1 class="row d-flex justify-content-center">
          {{ dish_type.name }}
          <a href="{% url 'catalog:dish-type-update' pk=dish_type.pk %}" class="btn btn-primary link-to-page">
            Update dish type
          </a>
        </h1>
          <p><strong>ID:</strong> {{ dish_type.id }}</p>
          <p><strong>Name:</strong> {{ dish_type.name }}</p>
        <h3>
          <a href="{% url 'catalog:dish-type-delete' pk=dish_type.pk %}" class="btn btn-danger link-to-page">
            Delete dish type
          </a>
        </h3>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/pages/dish_type_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} {{ object|yesno:"Update,Create" }} {% endblock title %}

{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">{{ object|yesno:"Update,Create" }}</h4>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Save</button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">Restaurant kitchen service</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/pages/dish_type_list.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Dish type List {% endblock title %}

{% block body %} {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}
  
<section class="pt-9 pb-5">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-6">
        <h1 class="row justify-content-center">
          Dish types
          <a href="{% url 'catalog:dish-type-create' %}" class="btn btn-primary">
            Create dish type
          </a>
        </h1>
        {% if dish_type_list %}
          {% include "includes/search_from.html" %}
          <table class="table">
            <tr>
              <th>ID</th>
              <th>Name</th>
            </tr>
          {% for dish_type in dish_type_list %}
            <tr>
              <td>{{ dish_type.id }}</td>
              <td><a class="link-primary" href="{% url 'catalog:dish-type-detail' pk=dish_type.pk %}"> {{ dish_type.name }}</a></td>
            </tr>
          {% endfor %}
          </table>
        {% else %}
          <p>There are no dish types.</p>
        {% endif %}
      
        {% include "includes/pagination.html" %}
      
      </div>
    </div>
  </div>
</section>
  
{% endblock content %}
  

templates/pages/index.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Restaurant Kitchen Service {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/curved-images/curved.jpg' %}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">RESTAURANT KITCHEN SERVICE</h1>
          <p class="lead text-white mt-3">Management system for cooks<br/> Here you can create new dishes & dish types and also specify cooks are responsible for every dishes cooking </p>
        </div>
      </div>
    </div>
    <div class="position-absolute w-100 z-index-1 bottom-0">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
          <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
        </g>
      </svg>
    </div>
  </div>
</header>
  
<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state1" countTo="70">{{ num_cooks }}</span>+</h1>
              <h5 class="mt-3">Cooks</h5>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"> <span id="state2" countTo="15">{{ num_dishes }}</span>+</h1>
              <h5 class="mt-3">Dishes</h5>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state3" countTo="4">{{ num_dish_types }}</h1>
              <h5 class="mt-3">Dish types</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  
<section class="my-1 pt-1">
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          <h4>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</h4>
        </div>
        <div class="col-md-5 ms-auto">
          <div class="position-relative">
            <img class="max-width-50 w-100 position-relative z-index-2" src="{% static 'img/illustrations/sign-up.png' %}" alt="image">
          </div>
        </div>
      </div>
    </div>
</section>
  
<section class="pt-1 pb-1 bg-gray-100" id="count-stats">
  <div class="container">
    <div class="text-start mb-5 mt-5">
      <h3 class="text-black z-index-1 position-relative text-center">We are trusted by:</h3>
    </div>
    <div class="row mb-7">
      <div class="col-lg-2 col-md-4 col-6 mb-4">
        <img class="w-100 opacity-7" src="{% static 'img/logos/gray-logos/logo-coinbase.svg' %}" alt="logo">
      </div>
      <div class="col-lg-2 col-md-4 col-6 mb-4">
        <img class="w-100 opacity-7" src="{% static 'img/logos/gray-logos/logo-nasa.svg' %}" alt="logo">
      </div>
      <div class="col-lg-2 col-md-4 col-6 mb-4">
        <img class="w-100 opacity-7" src="{% static 'img/logos/gray-logos/logo-netflix.svg' %}" alt="logo">
      </div>
      <div class="col-lg-2 col-md-4 col-6 mb-4">
        <img class="w-100 opacity-7" src="{% static 'img/logos/gray-logos/logo-pinterest.svg' %}" alt="logo">
      </div>
      <div class="col-lg-2 col-md-4 col-6 mb-4">
        <img class="w-100 opacity-7" src="{% static 'img/logos/gray-logos/logo-spotify.svg' %}" alt="logo">
      </div>
      <div class="col-lg-2 col-md-4 col-6 mb-4">
        <img class="w-100 opacity-7" src="{% static 'img/logos/gray-logos/logo-vodafone.svg' %}" alt="logo">
      </div>
    </div>
  </div>
</section>  
  
{% endblock content %}