catalog/urls.py
from django.urls import path

from .views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookYearOfExperienceUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    AssignDeleteDishView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dishtype/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dishtype/<int:pk>//detail/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "dishtype/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dishtype/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dishtype/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dish/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dish/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish/<int:pk>/toggle-assign/",
        AssignDeleteDishView.as_view(),
        name="toggle-dish-assign",
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookYearOfExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
]

app_name = "catalog"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer_background.html
{% load static %}

<footer class="footer pt-1 mt-1">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
        <div>
          <a href="/" rel="tooltip">
            <h6 class="text-gradient text-primary font-weight-bolder">RESTAURANT KITCHEN SERVICE</h6>
          </a>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <a href="{% url 'catalog:cook-list' %}">
            <h6 class="text-gradient text-primary text-sm">Cooks</h6>
          </a>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <a href="{% url 'catalog:dish-list' %}">
            <h6 class="text-gradient text-primary text-sm">Dishes</h6>
          </a>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
        <div>
          <a href="{% url 'catalog:dish-type-list' %}">
            <h6 class="text-gradient text-primary text-sm">Dish types</h6>
          </a>
        </div>
      </div>
      <div class="col-12">
        <div class="text-center">
          <p class="my-4 text-sm">
            &copy; <a href="/" rel="tooltip" target="_blank">RESTAURANT KITCHEN SERVICE</a> - Coded by Andrew13.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_signin.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-12 col-md-6 my-auto">
        <div class="copyright text-center text-sm text-white text-lg-start">
          &copy; <a class="font-weight-bold text-white" href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">Creative Tim</a> - Coded by AppSeed. 
        </div>
      </div>
      <div class="col-12 col-md-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com?AFFILIATE=128200" class="nav-link text-white" target="_blank">Creative Tim</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation?AFFILIATE=128200" class="nav-link text-white" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/blog?AFFILIATE=128200" class="nav-link text-white" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/license?AFFILIATE=128200" class="nav-link pe-0 text-white" target="_blank">License</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
{% load static %}
<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
        class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
            href="/" rel="tooltip"
            data-placement="bottom">
            RESTAURANT KITCHEN SERVICE
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
            data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="{% url 'catalog:cook-list' %}">
                  Cooks
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="{% url 'catalog:dish-list' %}">
                  Dishes
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                  href="{% url 'catalog:dish-type-list' %}">
                  Dish types
                </a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="nav-link nav-link-icon me-2">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                      data-bs-placement="bottom" title="Logout">Logout</p>
                  </button>
                </form>
              </li>
              {% else %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2"
                  href="{% url 'login' %}?next={{request.path}}">
                  <i class="fa fa-sign-in me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="Login">Login</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="link-to-page">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="link-to-page active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="link-to-page">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>

templates/includes/search_from.html
{% load crispy_forms_filters %}
<form action="" method="get" class="link-to-page">
  <div class="input-group" style="width: 500px">
    {{ search_form|crispy }}   
    <input type="submit" value="🔍" class="btn btn-primary" style="margin-left: 2px;
    border-top-left-radius: 15%;
    border-bottom-left-radius: 15%;">
  </div>
</form>
<br>